### ISSUE TITLE
Fatal error when target library is not found.

### ISSUE THREAD

**Issue by Iguana9999phil** [Cloudbox/autoscan#39] opened 2020-08-30 13:04 UTC
I have 3 Plex servers and not all got the same libraries (1080p only, 1080p with 4k and 1080P with 4K and 4K Remux)
Now when autoscan processes a remux it will have a fatal failure.

ERR Fatal error occurred while processing targets, processor stopped, triggers will continue... error="no target libraries found:

While I understand the thought behind it it would be better to (have the option) to not stop the processor and just continue with autoscan. 

PS: This wasn't a problem with plex_autoscan, it would just gracefully skip it and continue so a regression in function in that regard.

**Comment by m-rots** [comment] 2020-08-30 15:42
Right, this is a bit of an edge case in my opinion. The issue is marked as FATAL as 99% of users will only encounter this error when their rewrite rules are misconfigured or they have missing libraries. For this reason, I won't drop its fatal behaviour.

However, I'm not sure what the solution is either. The original PAS was not made with multiple Plex servers in mind and Autoscan *assumes* that your Plex servers have the same configuration when configuring multiple Plex targets.

I'm closing this issue for now as I think it's an edge case.

**Closed by m-rots** 2020-08-30 15:42 UTC

**Comment by Iguana9999phil** [comment] 2020-08-30 15:58
Yes the original PAS didn't work with multiple Plex servers hence why I set it up the way I did. While an Edge case as 99% of users don't have more than 1 Plex server anyway an advance setting to override this default would already be fine for those 1% who do have strange edge cases.
