### ISSUE TITLE
feature request : windows plex server + \\share\folder rewrite

### ISSUE THREAD

**Issue by warlordattack** [Cloudbox/autoscan#178] opened 2022-11-28 20:40 UTC
```
Hello i have one plex server on the synology ds198+ nas
and second plex server on my PC.
(nas server is only for local apple tv viewing, PC is for remote viewing because the nas has no enough transcoding power)

Nas access libraries like this : 
/volume1/partage/media/movies
/volume1/partage/media/music

PC access the same folders like this : 
\\dn\partage\media\movies
\\dn\partage\media\music

Tryed to do rewrite for windows like this : 
targets:
  plex:
    - url: http://my.nas:12345
      token: sdfsdfsdf
      rewrite:
        - from: /partage/
          to: /volume1/partage/
        - from: /partaget/
          to: /volume1/partaget/
    - url: http://my.pc:12346
      token: sdfsdfsdfs
      rewrite:
        - from: /partage/
          to: \\dn\partage\
        - from: /partaget/
          to: \\dn\partaget\

Unfortunately for windows this doesn't work : 
        - from: /partaget/
          to: \\dn\partaget\

Error in the log : 
11/28/2022 9:29:30 PM
Nov 28 21:29:30 WRN No target libraries found error="\\\\\\\\dn\\\\partage\\\\media/movies/Pearl (2022): failed determining libraries" target=plex url=http://my.pc:12346

I saw you suggested WSL, but unfortunatly with WSL i can't use my RTX 3070 to do transcoding with Plex, so i use native Windows Plex server app.

```

**Comment by m-rots** [comment] 2022-12-02 15:14
We currently have no plans for Windows support, but we are open to proposals on how to best implement Windows path rewriting. A couple of remarks from my side:
- It cannot be a global switch. E.g. if Autoscan is running on Windows, then not all paths can be expected to be Windows-friendly as this would break other remote triggers and targets which use the current UNIX path scheme.
- It could be an extra option to the `rewrite` config module. A unix/windows boolean toggle isn't really future proof. So either we introduce some kind of `os` enumeration with `unix` and `windows` as expected values, with unix being the default. Alternatively, we can abstract away the operating system and introduce a `slash-direction` option or something similarly named, with `forward` and `backward` options.

For now though, I'm closing this as a duplicate of #111.

**Closed** 2022-12-02 15:15 UTC

**Comment by nullip** [comment] 2023-01-03 17:35
Just to note on this, at least with Emby if you utilize UNC network paths in your rewrite such as
 rewrite:
        - from: /media/media/
          to: \\?\UNC\server\media\media\

it will rewrite the paths to \\\\?\\UNC\\server\\media\\media\\anime/madeupanimename/Season 1

Which "appears" to be working at least in the capacity of it scanning the library, unsure if it is just scanning exactly what it says it's trying to or if it is triggering a scan of the entire library.
