### ISSUE TITLE
Intro detection

### ISSUE THREAD

**Issue by JohnFawkes** [Cloudbox/autoscan#196] opened 2023-01-30 06:28 UTC
So I've been using autoscan for awhile now and it's working great. Only issue have with it currently is intro detection. Normally when plex scans in media I have it set to do its intro detection for tvshows. When autoscan triggers the scan that doesn't happen. I have to run a full scan or wait for the schedule. Is there any way to trigger the intro detection when autoscan triggers a scan?

**Comment by m-rots** [comment] 2023-01-31 16:34
As far as we are aware we cannot signal to Plex that it should refresh the metadata (or perform a full analysis) of the requested item. For some more background information please check out the thread in #134. For now I'm closing this issue as a duplicate of #105.

**Closed by m-rots** 2023-01-31 16:34 UTC
