### ISSUE TITLE
Will support refreshing metadata?

### ISSUE THREAD

**Issue by kolicime** [Cloudbox/autoscan#163] opened 2022-07-29 14:50 UTC
For subtitle files, only refreshing the metadata can make them available in PLEX. But currently autoscan seems to support only scanning libraries. Is it possible to add the operation of refreshing metadata? Here is an API for reference:  https://www.reddit.com/r/PleX/comments/pwi9jg/use_api_to_refresh_metadata_for_a_single_artist/

Autoscan is an excellent project, thank you for your dedication to it, and I think it would be even better if this problem could be solved. :)

**Comment by amwamw968** [comment] 2022-08-22 09:37
let the autoscan support to auto scan everythings!

**Comment by dantebarba** [comment] 2022-11-21 03:00
Oh so thats why my bazarr script wasn't working!

**Comment by dantebarba** [comment] 2022-11-21 03:08
Ok so: 

https://github.com/Cloudbox/autoscan/blob/63edb8ee5a69fc6ae6fc8f1229c53cf6a61bc927/targets/plex/api.go#L150

This should also include a PUT line to update the metadata. I could try to do it myself and then request a PR.

**Comment by dantebarba** [comment] 2022-11-21 21:51
I created a tool/app to refresh the metadata. You can check it out here. It works in companion with autoscan

https://github.com/dantebarba/autoscan-adapter

**Comment by m-rots** [comment] 2022-12-02 15:21
Unfortunately, Plex still doesn't offer an officially supported API method to ensure that metadata is refreshed (see the #134 thread). Therefore I'm closing this issue as a duplicate of #105.

**Closed by m-rots** 2022-12-02 15:21 UTC
